name: Equidna
options:
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  generateSchemes: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"

targets:
  EquidnaApp:
    type: application
    platform: iOS
    sources:
      - path: Equidna
    resources:
      - path: Equidna/Assets.xcassets
      - path: Equidna/Base.lproj
    entitlements:
      generate: true
      path: Equidna/Equidna.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.Gardinidev.EquidnaApp
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.security.application-groups:
          - group.Gardinidev.EquidnaApp
    settings:
      base:
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Precisamos salvar suas fotos/vídeos no app Fotos."
        PRODUCT_BUNDLE_IDENTIFIER: gardinidev.EquidnaApp
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_NAME: Equidna
        CURRENT_PROJECT_VERSION: 0.1
    dependencies: []

  EquidnaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: EquidnaTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: gardinidev.EquidnaTests
    dependencies:
      - target: EquidnaApp

  WidgetEquidna:
    type: app-extension
    platform: iOS
    sources:
      - path: WidgetEquidna
    entitlements:
      generate: true
      path: WidgetEquidna/WidgetEquidna.entitlements
      properties:
        com.apple.security.application-groups:
          - group.Gardinidev.EquidnaApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 0.1
        PRODUCT_BUNDLE_IDENTIFIER: gardinidev.WidgetEquidna
        # INFOPLIST_KEY_NSExtension:
        #   NSExtensionPointIdentifier: com.apple.widgetkit-extension
        #   NSExtensionPrincipalClass: ""
        INFOPLIST_KEY_CFBundleDisplayName: "My Widget"
    dependencies:
      - target: EquidnaApp
      - framework: WidgetKit
